<?php

namespace LxEnqueue\Facades;

use Illuminate\Support\Facades\Facade;

/**
 * Class LxEnqueue
 * @package LxEnqueue\Facades
 * @method static produce
 * @method static connection
 */
class LxEnqueue extends Facade
{
    protected static function getFacadeAccessor()
    {
        // TODO: Change the autogenerated stub
    }
}
